[workspace]
members = ["yatzy", "yatzy-compute-expected-values", "yatzy-solver"]
resolver = "3"

[workspace.dependencies]
yatzy = { path = "yatzy" }
yatzy-compute-expected-values = { path = "yatzy-compute-expected-values" }
