[workspace]
members = ["yatzy", "yatzy-compute-expected-values", "yatzy-solver", "yatzy-web"]
resolver = "3"

[workspace.dependencies]
yatzy = { path = "yatzy" }
yatzy-compute-expected-values = { path = "yatzy-compute-expected-values" }
yatzy-solver = { path = "yatzy-solver" }
